# Generated by Django 5.0.14 on 2025-04-22 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='titre')),
                ('url', models.CharField(default='', max_length=256)),
                ('picture_url', models.CharField(default='', max_length=256)),
                ('synopsis', models.CharField(default='', max_length=1500)),
                ('predicted_affluence', models.PositiveIntegerField(default=0, verbose_name='Affluence prédite')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
