# Generated by Django 5.0.14 on 2025-04-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='real_affluence',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Affluence réelle'),
        ),
    ]
