# Generated by Django 5.0.14 on 2025-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_real_affluence'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='predicted_affluence_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Affluence prédite 2'),
        ),
        migrations.AddField(
            model_name='movie',
            name='shap_values',
            field=models.TextField(default='', verbose_name='Shap values'),
        ),
        migrations.AddField(
            model_name='movie',
            name='shap_values_2',
            field=models.TextField(default='', verbose_name='Shap values 2'),
        ),
    ]
