FROM python:3.11-slim

# Installer dépendances système nécessaires (Scrapy et autres)
RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2-dev \
    libxslt1-dev \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copier requirements.txt spécifique à allocine_scrapping
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copier le code source de allocine_scrapping
COPY . .

# Commande par défaut : lancer le runner Python
CMD ["python", "runner.py"]